export const siteConfig = {
  name: 'امداد خودرو افاق',
  description: 'خدمات امدادی و یدک کش خودرو در استان اصفهان و جاده های حومه',
  landingHeaderNavigationLinks: [
    { label: 'درباره ما', href: '#aboutus' },
    { label: 'خدمات', href: '#services' },
    { label: 'گالری', href: '#gallery' },
    { label: 'نظرات مشتریان', href: '#reviews' },
    { label: 'سوالات رایج', href: '#faq' },
    { label: 'تماس با ما', href: '#contactus' },
  ],
  headerNavigationLinks: [
    { label: 'درباره ما', href: '/aboutus' },
    { label: 'خدمات', href: '/services' },
    { label: 'گالری', href: '/gallery' },
    { label: 'نظرات مشتریان', href: '/reviews' },
    { label: 'سوالات رایج', href: '/faq' },
    { label: 'تماس با ما', href: '/contactus' },
  ],
  landingHeaderMenuLinks: [
    { label: 'صفحه اصلی', href: '/' },
    { label: 'درباره ما', href: '#aboutus' },
    { label: 'خدمات', href: '#services' },
    { label: 'گالری', href: '#gallery' },
    { label: 'نظرات مشتریان', href: '#reviews' },
    { label: 'سوالات رایج', href: '#faq' },
    { label: 'تماس با ما', href: '#contactus' },
  ],
  headerMenuLinks: [
    { label: 'صفحه اصلی', href: '/' },
    { label: 'درباره ما', href: '/aboutus' },
    { label: 'خدمات', href: '/services' },
    { label: 'گالری', href: '/gallery' },
    { label: 'نظرات مشتریان', href: '/reviews' },
    { label: 'سوالات رایج', href: '/faq' },
    { label: 'تماس با ما', href: '/contactus' },
  ],
  headerActionsLinks: [
    { id: 'login', label: 'ورود', href: '/login', target: '_blank' },
    { id: 'register', label: 'ثبت نام', href: '/register', target: '_blank' },
  ],
  footerBrandLinks: [
    { id: 'about-us', label: 'درباره ما', href: '#aboutus', target: '_blank' },
    { id: 'services', label: 'خدمات', href: '#services', target: '_blank' },
    { id: 'gallery', label: 'گالری', href: '#gallery', target: '_blank' },
  ],
  footerCustomerLinks: [
    { id: 'faqs', label: 'پرسش پاسخ', href: '#faq', target: '_blank' },
    { id: 'reviews', label: 'بازخورد ها', href: '#reviews', target: '_blank' },
    { id: 'support', label: 'پشتیبانی', href: '/support', target: '_blank' },
  ],
  footerServiceLinks: [
    { id: 'news', label: 'اخبار', href: '/news', target: '_blank' },
    {
      id: 'complaint',
      label: 'ثبت شکایت',
      href: '/complaint',
      target: '_blank',
    },
    {
      id: 'contact-us',
      label: 'تماس با ما',
      href: '#contactus',
      target: '_blank',
    },
  ],
  footerBlogLinks: [
    { id: 'post-1', label: 'تعویض باتری', href: '#changeb', target: '_blank' },
    { id: 'post-2', label: 'تعویض لنت', href: '#changel', target: '_blank' },
    { id: 'blog', label: 'پست های بیشتر', href: '/blog', target: '_blank' },
  ],
  //TODO: Update social links
  footerSocial: [
    {
      id: 'rubika',
      label: 'RubikaIcon',
      href: '#rubika',
      name: 'روبیکا',
      target: '_blank',
    },
    {
      id: 'whatsapp',
      label: 'WhatsAppIcon',
      href: '#whatsapp',
      name: 'واتساپ',
      target: '_blank',
    },
    {
      id: 'instagram',
      label: 'InstagramIcon',
      href: '#instagram',
      name: 'اینستاگرام',
      target: '_blank',
    },
    {
      id: 'telegram',
      label: 'TelegramIcon',
      href: '#telegram',
      name: 'تلگرام',
      target: '_blank',
    },
    {
      id: 'bale',
      label: 'BaleIcon',
      href: '#bale',
      name: 'بله',
      target: '_blank',
    },
  ],
  footerSiteInfo: [
    { id: 'terms', label: 'شرایط استفاده', href: '/terms', target: '_blank' },
    {
      id: 'developer',
      label: 'سایت از مجموعه ی دانا',
      href: 'https://www.danadev.com',
      target: '_blank',
    },
    {
      id: 'policies',
      label: 'حریم خصوصی',
      href: '/policies',
      target: '_blank',
    },
  ],
  aboutUsCities: [
    {
      id: 'اصفهان',
      label: 'اصفهان',
      href: 'esfahan',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر اصفهان',
      target: '',
    },
    {
      id: 'کاشان',
      label: 'کاشان',
      href: 'kashan',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر کاشان',
      target: '',
    },
    {
      id: 'خمینی‌شهر',
      label: 'خمینی‌شهر',
      href: 'khomeinishahr',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر خمینی‌شهر',
      target: '',
    },
    {
      id: 'نجف‌آباد',
      label: 'نجف‌آباد',
      href: 'najafabad',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر نجف‌آباد',
      target: '',
    },
    {
      id: 'لنجان',
      label: 'لنجان',
      href: 'lenjan',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر لنجان',
      target: '',
    },
    {
      id: 'فلاورجان',
      label: 'فلاورجان',
      href: 'falavarjan',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر فلاورجان',
      target: '',
    },
    {
      id: 'شاهین‌شهر',
      label: 'شاهین‌شهر',
      href: 'shahinshahr',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر شاهین‌شهر',
      target: '',
    },
    {
      id: 'شهرضا',
      label: 'شهرضا',
      href: 'shahreza',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر شهرضا',
      target: '',
    },
    {
      id: 'مبارکه',
      label: 'مبارکه',
      href: 'mobarakeh',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر مبارکه',
      target: '',
    },
    {
      id: 'برخوار',
      label: 'برخوار',
      href: 'barakhur',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر برخوار',
      target: '',
    },
    {
      id: 'آران و بیدگل',
      label: 'آران و بیدگل',
      href: 'aran-va-bidgol',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر آران و بیدگل',
      target: '',
    },
    {
      id: 'سمیرم',
      label: 'سمیرم',
      href: 'semirom',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر سمیرم',
      target: '',
    },
    {
      id: 'گلپایگان',
      label: 'گلپایگان',
      href: 'golpayegan',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر گلپایگان',
      target: '_blank',
    },
    {
      id: 'تیران و کرون',
      label: 'تیران و کرون',
      href: 'tiran',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر تیران و کرون',
      target: '',
    },
    {
      id: 'فریدن',
      label: 'فریدن',
      href: 'fereydun',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر فریدن',
      target: '',
    },
    {
      id: 'نطنز',
      label: 'نطنز',
      href: 'natanz',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر نطنز',
      target: '',
    },
    {
      id: 'اردستان',
      label: 'اردستان',
      href: 'ardistan',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر اردستان',
      target: '',
    },
    {
      id: 'نائین',
      label: 'نائین',
      href: 'nain',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر نائین',
      target: '',
    },
    {
      id: 'جرقویه',
      label: 'جرقویه',
      href: 'jorqooyeh',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر جرقویه',
      target: '',
    },
    {
      id: 'فریدون‌شهر',
      label: 'فریدون‌شهر',
      href: 'fereydunshahr',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر فریدون‌شهر',
      target: '',
    },
    {
      id: 'دهاقان',
      label: 'دهاقان',
      href: 'dehaghan',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر دهاقان',
      target: '',
    },
    {
      id: 'خوانسار',
      label: 'خوانسار',
      href: 'khvansar',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر خوانسار',
      target: '',
    },
    {
      id: 'چادگان',
      label: 'چادگان',
      href: 'chadegan',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر چادگان',
      target: '',
    },
    {
      id: 'ورزنه',
      label: 'ورزنه',
      href: 'varzaneh',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر ورزنه',
      target: '',
    },
    {
      id: 'بوئین و میاندشت',
      label: 'بوئین و میاندشت',
      href: 'buin-va-miandasht',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر بوئین و میاندشت',
      target: '',
    },
    {
      id: 'کوهپایه',
      label: 'کوهپایه',
      href: 'koohpayeh',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر کوهپایه',
      target: '',
    },
    {
      id: 'هرند',
      label: 'هرند',
      href: 'harand',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر هرند',
      target: '',
    },
    {
      id: 'خور و بیابانک',
      label: 'خور و بیابانک',
      href: 'khor',
      src: '/media/imgs/hamrah/handDrawn/hm_2.png',
      alt: 'تصویر خور و بیابانک',
      target: '',
    },
  ],
};
